# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: mini-sql release

on:
  push:
    branches: [ master ]
  release:
    types: [created]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@main
    - name: Set up JDK 17
      uses: actions/setup-java@main
      with:
        java-version: '17'
        distribution: 'temurin'
        java-package: 'jdk'
        cache: 'maven'
        server-id: central

    - name: Import GPG Key
      uses: crazy-max/ghaction-import-gpg@v6
      with:
        gpg_private_key: ${{ secrets.MAVEN_GPG_SECRET_KEY }}
        passphrase: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

    - name: Build with Maven
      run: mvn --batch-mode --file pom.xml clean install

    - name: Publish to Central Maven Repo
      run: mvn --batch-mode deploy --file ./hironico-dist/pom.xml -s settings.xml
      env:
        PGP_KEY_NAME: ${{ secrets.MAVEN_GPG_KEY_NAME }}
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
